logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web: debug
#    org.springframework.web: ERROR
    com.swim.dao: debug
    logging.level.*: debug
    logging.level.org.springframework: debug
#    logging.path= /var/log: 默认的日志路径配置
#    logging.pattern.level: 日志等级的格式渲染，只支持logback
#    logging.pattern.console: 控制台日志的格式，只支持logback
#    logging.pattern.file: 日志文件中日志的格式，只支持logback
    logging.register-shutdown-hook: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_swim?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #jdbc:mysql://127.0.0.1:3306/my_db?useUnicode=true&characterEncoding=utf-8   
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
#    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /static

#  http:
#    multipart:
#      enabled: true
#      max-file-size: 5MB
#      max-request-size: 5MB
#      location: /static
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  #  profiles: dev
#  profil:
#    test: 开发

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  redis:
    host: 127.0.0.1
    port: 6379
  output:
    ansi:
      enabled: always
#  http:
#    encoding:
#      charset: utf-8
#      force: true
#      enabled: true
server:
  tomcat:
    uri-encoding: utf-8
mybatis:
  type-aliases-package: com.swim.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/*.xml